

name: Hello Actions

on:
  push:
    branches:
    - main
    - master # old type
  pull_request:
    branches:
    - main
    - master # old type
jobs:
  build:
    name: "Hellow world action"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : Print something
        uses: ./actions/print
        with:
          text: "Hello from action 1"
      - name: Print something
        uses : ./actions/bye
        with:
          name: "Sandun"
      - name: Show run number
        run: echo "This is workflow run number ${{ github.run_number }} ${{github.run_id}} ${{github.workflow}} ${{github.ref}}"